### ISSUE TITLE
感谢大佬的脚本，两天钻5了，发现一些bug

### ISSUE THREAD

**Issue by luckpoi** [xjw580/Hearthstone-Script#1]
首先是地标不能攻击，会导致一直烧绳不攻击
然后有时候点两遍开始就容易崩溃
希望还能改进一下牌序，二费能跳币，图腾巨人的上场，以及面对快攻（根据对方场上随从数量）时早点交图腾加血加攻

**Comment by xjw580** [comment]
然后建议把此问题在Gitee上提Issue，方便我统一查看。




闲物
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjw580/Hearthstone-Script"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月20日(星期一) 凌晨0:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xjw580/Hearthstone-Script] 感谢大佬的脚本，两天钻5了，发现一些bug (Issue #1)





 
首先是地标不能攻击，会导致一直烧绳不攻击
 然后有时候点两遍开始就容易崩溃
 希望还能改进一下牌序，二费能跳币，图腾巨人的上场，以及面对快攻（根据对方场上随从数量）时早点交图腾加血加攻

**Comment by xjw580** [comment]
刚工作，等我下月发工资配完台式机后再优化这些逻辑问题，目前先凑合用吧。
