### ISSUE TITLE
[Bug]: 运行一段时间后，自己点入我的收藏然后不知道在干什么

### ISSUE THREAD

**Issue by huanghaiji666666** [xjw580/Hearthstone-Script#100]
### 预期情况

进入传统对战

### 实际情况

进入了收藏界面然后点开一张卡，停住

### 复现方法

长时间挂机就会出现

### 日志信息

![image](https://github.com/user-attachments/assets/07375d17-248b-4335-ac1a-942a01a57a67)
[hs_script.log](https://github.com/user-attachments/files/17928422/hs_script.log)

### 我确认已更新至最新版本

- [X] 是

### 我确认已查询历史issues及参阅QUESTION

- [X] 是

**Comment by xjw580** [comment]
下个版本优化

**Comment by xjw580** [comment]
v4.2.2-DEV已优化
