### ISSUE TITLE
增加表情和自动投降

### ISSUE THREAD

**Issue by LuoShen1512** [xjw580/Hearthstone-Script#102]
### 相关问题

是否可以增加一个【求全策略】

### 描述你希望的解决方案

如果大部分封号都是被对手举报引起的话，那是否能在【激进策略】的基础上，增加一个【求全策略】，具体方向大概是1、增加每个回合结束前，想对手问好；2、在第十个回合后自动投降。我目前想到就是这两项，感觉可以减少对面的脚本怀疑和打不赢举报的心理，从而达到安稳挂机获取经验的目的。谢谢

### 我确认已查询历史issues

- [X] 是

**Comment by xjw580** [comment]
这个不需要写到插件策略里，下个版本将会在设置里添加这两项

**Comment by LuoShen1512** [comment]
> 这个不需要写到插件策略里，下个版本将会在设置里添加这两项
大佬nb

**Comment by xjw580** [comment]
`v4.2.3-TES` 已增加
