### ISSUE TITLE
反复提示下载jdk21

### ISSUE THREAD

**Issue by zjbfshuimen** [xjw580/Hearthstone-Script#107]
### 相关问题

为什么打开hs-script后浏览器安装jdk21，不适用默认安装路径之后再将jdk21的bin增加到环境变量后再打开hs-script还是提示下载jdk21

### 描述你希望的解决方案

在环境变量查阅jdk

### 我确认已查询历史issues

- [X] 是

**Comment by xjw580** [comment]
执行java -version，看下输出

**Comment by zjbfshuimen** [comment]
原来是因为已经安装jdk17，用jdk21把17的path替换掉就行了
