### ISSUE TITLE
[Feature request]: 支持卡组的选择

### ISSUE THREAD

**Issue by shiquda** [xjw580/Hearthstone-Script#109]
### 相关问题

现在的挂机卡组选择，似乎只能选择第一个卡组，在新创建卡组的时候会被顶下去，还需要手动操作换到第一个

### 描述你希望的解决方案

可以在设置中选择使用进行挂机的卡组，比如第一页的第4个

### 我确认已查询历史issues

- [X] 是

**Comment by xjw580** [comment]
设置成第一页的第4个在创建新卡组时不还是会被顶下去嘛

**Comment by shiquda** [comment]
> 设置成第一页的第4个在创建新卡组时不还是会被顶下去嘛

这样可以选择之后，挂机就可以直接在脚本那边设置了，而不是把要挂机的卡组再在游戏里面复制一遍，然后创建为第一个卡组

**Comment by xjw580** [comment]
`v4.3.0-GA`已添加
