### ISSUE TITLE
能不能添加狂野模式选项？

### ISSUE THREAD

**Issue by gracekk** [xjw580/Hearthstone-Script#11]
谢谢

**Comment by xjw580** [comment]
> 谢谢

后续会将偶数萨移植回来

**Comment by gracekk** [comment]
快捷键能否加个自定义:)

**Comment by xjw580** [comment]
> 快捷键能否加个自定义:)

可

**Comment by gracekk** [comment]
再次谢谢作者大大，有个问题: 

power.log即将达到24576KB，准备重启游戏
过大后必须重启游戏吗？ 有没有优化的可能？

**Comment by xjw580** [comment]
> 再次谢谢作者大大，有个问题:
> 
> power.log即将达到24576KB，准备重启游戏 过大后必须重启游戏吗？ 有没有优化的可能？

游戏默认日志大小10*1024KB,我调大了一点，下个版本可以再调大一点。日志超过大小游戏就不会打印日志了，只能重启游戏才会打印新的日志
