### ISSUE TITLE
[Feature request]: 增加攻击权重

### ISSUE THREAD

**Issue by LuoShen1512** [xjw580/Hearthstone-Script#110]
### 相关问题

是否可以增加一个攻击权重

### 描述你希望的解决方案

使得一些特定的随从，不攻击  只是站场

### 我确认已查询历史issues

- [X] 是

**Comment by LuoShen1512** [comment]
比如这种随从
![image](https://github.com/user-attachments/assets/187e7508-3ed5-4cc9-b2e9-69ff3d806974)

**Comment by xjw580** [comment]
建议自行编写插件
