### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by gracekk** [xjw580/Hearthstone-Script#16]
用github workflow build成功，准备提pr，然后发现无法运行，帮忙看下有什么问题？

(删除了lib目录下的其他组件）

[hs-script_v4.0.0.1-PATCH.zip](https://github.com/user-attachments/files/17165080/hs-script_v4.0.0.1-PATCH.zip)

**Comment by xjw580** [comment]
lib目录的依赖都被你删完了，肯定跑不起来呀😂

**Comment by gracekk** [comment]
> lib目录的依赖都被你删完了，肯定跑不起来呀😂

不是，我是为了能够上传，全部传太大了，github限制25M。
我编译出来的运行不起来
