### ISSUE TITLE
大佬，原来的偶数萨在美区可以正常使用，国服啥时候上偶数萨？

### ISSUE THREAD

**Issue by 1987Lr1987** [xjw580/Hearthstone-Script#17]

**Comment by xjw580** [comment]
这个版本对项目重构了一部分，目前还没重构完，原来偶数萨的代码不兼容，啥时候有空再兼容

**Comment by 1987Lr1987** [comment]
大佬，现在国服使用的新版本里面的支持套牌和卡牌插件有点不明白啥意思，卡牌插件就是记牌器同类？套牌的话暂时只支持无战吼和法术的套牌对吧，后续会新增通用策略（狂野通用，标准通用）？

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月27日 22:48 |
| 收件人 | xjw580/Hearthstone-Script ***@***.***> |
| 抄送人 | 1987Lr1987 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [xjw580/Hearthstone-Script] 大佬，原来的偶数萨在美区可以正常使用，国服啥时候上偶数萨？ (Issue #17) |

这个版本对项目重构了一部分，目前还没重构完，原来偶数萨的代码不兼容，啥时候有空再兼容

**Comment by xjw580** [comment]
> 大佬，现在国服使用的新版本里面的支持套牌和卡牌插件有点不明白啥意思，卡牌插件就是记牌器同类？套牌的话暂时只支持无战吼和法术的套牌对吧，后续会新增通用策略（狂野通用，标准通用）？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年09月27日 22:48 | | 收件人 | xjw580/Hearthstone-Script ***@***.***> | | 抄送人 | 1987Lr1987 ***@***.***>, Author ***@***.***> | | 主题 | Re: [xjw580/Hearthstone-Script] 大佬，原来的偶数萨在美区可以正常使用，国服啥时候上偶数萨？ (Issue #17) | 这个版本对项目重构了一部分，目前还没重构完，原来偶数萨的代码不兼容，啥时候有空再兼容 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

就是套牌策略插件化了，支持自己编写套牌策略插件放入plugin目录下，软件会自行读取。而卡牌插件就是为了让脚本知道要怎么出不同的牌，比如某些带发现的战吼牌从手里丢出去还要发现卡牌，又比如有些造成伤害的战吼牌丢出去后需要选定攻击目标，这些都是需要卡牌插件去定义，不然就像现在一样只能打出无战吼的随从，因为脚本不知道那些法术或战吼打出后需要进行的操作，直接打出很可能卡住。
