### ISSUE TITLE
如何开发一个插件

### ISSUE THREAD

**Issue by konmor** [xjw580/Hearthstone-Script#19]
如题，会点代码，java。如何开发呢

**Comment by xjw580** [comment]
可先参考[此处](https://github.com/xjw580/Hearthstone-Script/#%E6%8F%92%E4%BB%B6%E6%94%AF%E6%8C%81)
稍晚将更新详细步骤

**Comment by konmor** [comment]
![223F1915B4AD286B129B82DC3EA8FE2D](https://github.com/user-attachments/assets/a24a7402-70f0-407b-8528-c185981032d8)

**Comment by xjw580** [comment]
> ![223F1915B4AD286B129B82DC3EA8FE2D](https://private-user-images.githubusercontent.com/55009868/371832961-a24a7402-70f0-407b-8528-c185981032d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDg5MDcsIm5iZiI6MTcyNzYwODYwNywicGF0aCI6Ii81NTAwOTg2OC8zNzE4MzI5NjEtYTI0YTc0MDItNzBmMC00MDdiLTg1MjgtYzE4NTk4MTAzMmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDExMTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5Y2RiZjZkNzQ5NTUzNzRmZDc3M2NhYWVjN2ViODdkNjU4MzZhNDE4OGJkYTcwN2VmN2NmMjZjMjAyNDc0MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YwgABjLLMOf-uuiTTU8h4-lvGzvgRqIzQ7gQMmok-Rg)

[插件开发文档](https://github.com/xjw580/Hearthstone-Script/blob/master/PLUGIN_DEV.md)已经可用
