### ISSUE TITLE
如何编写一个套牌策略放置在插件下

### ISSUE THREAD

**Issue by xiatianlaila** [xjw580/Hearthstone-Script#20]
大佬可以出一个 simple demo 说明下怎样编写套牌策略吗，因为现在不带法术的套牌太少了

**Comment by xjw580** [comment]
参考[插件开发](https://github.com/xjw580/Hearthstone-Script/blob/master/PLUGIN_DEV.md/#%E6%8F%92%E4%BB%B6%E5%BC%80%E5%8F%91%E6%AD%A5%E9%AA%A4)
