### ISSUE TITLE
场上有七个随从时还是会一直往场上拖随从，然后会卡很久

### ISSUE THREAD

**Issue by jcjc0326** [xjw580/Hearthstone-Script#25]
能否加个判定，当上随从到7个时先让随从攻击
[Uploading hs_script-2024-10-06.1.log…]()

**Comment by xjw580** [comment]
可以。下怪的时候没有做满场判定，下个补丁修复

**Comment by xjw580** [comment]
[v4.0.0.3-PATCH](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.0.0.3-PATCH) 中修复
