### ISSUE TITLE
挂机时会进入到我的收藏，然后卡住

### ISSUE THREAD

**Issue by 1987Lr1987** [xjw580/Hearthstone-Script#3]

**Comment by 1987Lr1987** [comment]
大佬，是否能加入其他套牌，比如基础套牌或者新任务送的免费套牌，用于新手使用

**Comment by xjw580** [comment]
这是因为主界面那个弹窗的关闭按钮和我的收藏位置有点接近，然后我设置鼠标点击加了随机数，所以有概率点进我的收藏，但是按道理不会一直卡住，5分钟后会关闭游戏重新进的，

**Comment by xjw580** [comment]
然后本项目现已进入停更维护阶段，国服回归后恢复更新

**Comment by 1987Lr1987** [comment]
感谢回复，一开始以为是分辨率问题，改了后也会发生，最近刚入美服，您的辅助很好用，偶数萨狂野天梯最高白金1，很难直接传说，但是还是要感谢大佬

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月30日 11:29 |
| 收件人 | xjw580/Hearthstone-Script ***@***.***> |
| 抄送人 | 1987Lr1987 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [xjw580/Hearthstone-Script] 挂机时会进入到我的收藏，然后卡住 (Issue #3) |

然后本项目现已进入停更维护阶段，国服回归后恢复更新

**Comment by xjw580** [comment]
> 感谢回复，一开始以为是分辨率问题，改了后也会发生，最近刚入美服，您的辅助很好用，偶数萨狂野天梯最高白金1，很难直接传说，但是还是要感谢大佬
> 
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 发送日期 | 2024年01月30日 11:29 |
> | 收件人 | xjw580/Hearthstone-Script ***@***.***> |
> | 抄送人 | 1987Lr1987 ***@***.***>,
> Author ***@***.***> |
> | 主题 | Re: [xjw580/Hearthstone-Script] 挂机时会进入到我的收藏，然后卡住 (Issue #3) |
> 
> 然后本项目现已进入停更维护阶段，国服回归后恢复更新
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

等国服回归了再把偶数萨逻辑优化一下，在亚服用月中的时候还是能传说的，毕竟亚服脚本多😂

**Comment by 1987Lr1987** [comment]
大佬，打扰了，有没有推荐的战祺的脚本，打扰了

**Comment by xjw580** [comment]
没有
&nbsp;


闲物
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月31日(星期三) 晚上6:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [xjw580/Hearthstone-Script] 挂机时会进入到我的收藏，然后卡住 (Issue #3)





 
大佬，打扰了，有没有推荐的战祺的脚本，打扰了
