### ISSUE TITLE
请问各位大佬能否回复几个效率比较高的卡组，多谢啦。

### ISSUE THREAD

**Issue by H2annibal** [xjw580/Hearthstone-Script#31]
请问各位大佬能否回复几个效率比较高的卡组，多谢啦。

**Comment by robot-2233** [comment]
### 123
# 职业：死亡骑士
# 模式：标准模式
# 天马年
#
# 2x (1) 得胜的维库人
# 2x (1) 鱼人招潮者
# 2x (1) 鱼人木乃伊
# 2x (2) 交际鱼人
# 2x (2) 仙人掌暴怒者
# 2x (2) 困苦的克瓦迪尔
# 2x (2) 战利品贮藏者
# 2x (2) 战场通灵师
# 2x (2) 淘金客
# 2x (2) 精灵龙
# 2x (2) 雏龙牧人
# 2x (2) 音乐治疗师
# 2x (3) 团队领袖
# 2x (4) 酷炫的食尸鬼
# 1x (0) 奇利亚斯豪华版3000型
#   1x (0) 奇利亚斯豪华版3000型
#   1x (3) 输能模块
#   1x (4) 计数模块
# 1x (20) 矿坑老板雷斯卡
# 
AAECAfHhBAL/lwbHpAYOoZ8EoaAEq6AEqdQEkeQEy8QFkOQFnfYF9fcFkY4G1ZgGzpwG8ZwG1J4GAAED87MGx6QG9rMGx6QG7t4Gx6QGAAA=
# 
# 想要使用这副套牌，请先复制到剪贴板，然后在游戏中点击“新套牌”进行粘贴。

**Comment by H2annibal** [comment]
收到，非常感谢。





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bomb-sniffing Pomeranian ***@***.***&gt;
发送时间: 2024年10月16日 10:21
收件人: xjw580/Hearthstone-Script ***@***.***&gt;
抄送: H2annibal ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [xjw580/Hearthstone-Script] 请问各位大佬能否回复几个效率比较高的卡组，多谢啦。 (Issue #31)

**Comment by H2annibal** [comment]
不知道策略是否有更新，挂了一段时间发现胜率差不多10%几，非常低。不知道有没有什么方式进行优化，多谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bomb-sniffing Pomeranian ***@***.***&gt;
发送时间: 2024年10月16日 10:21
收件人: xjw580/Hearthstone-Script ***@***.***&gt;
抄送: H2annibal ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [xjw580/Hearthstone-Script] 请问各位大佬能否回复几个效率比较高的卡组，多谢啦。 (Issue #31)





 
123
 
职业：死亡骑士
 
模式：标准模式
 
天马年
 

 
2x (1) 得胜的维库人
 
2x (1) 鱼人招潮者
 
2x (1) 鱼人木乃伊
 
2x (2) 交际鱼人
 
2x (2) 仙人掌暴怒者
 
2x (2) 困苦的克瓦迪尔
 
2x (2) 战利品贮藏者
 
2x (2) 战场通灵师
 
2x (2) 淘金客
 
2x (2) 精灵龙
 
2x (2) 雏龙牧人
 
2x (2) 音乐治疗师
 
2x (3) 团队领袖
 
2x (4) 酷炫的食尸鬼
 
1x (0) 奇利亚斯豪华版3000型
 
1x (0) 奇利亚斯豪华版3000型
 
1x (3) 输能模块
 
1x (4) 计数模块
 
1x (20) 矿坑老板雷斯卡
 

 
AAECAfHhBAL/lwbHpAYOoZ8EoaAEq6AEqdQEkeQEy8QFkOQFnfYF9fcFkY4G1ZgGzpwG8ZwG1J4GAAED87MGx6QG9rMGx6QG7t4Gx6QGAAA=
 

 
想要使用这副套牌，请先复制到剪贴板，然后在游戏中点击“新套牌”进行粘贴。

**Comment by robot-2233** [comment]
目前我也没有找到更好的卡组 也欢迎你分享下卡组
因为根据我的观察 coder应该是检测卡牌是否有战吼 有的话就一直憋手里 这样其实限定了很多卡牌不能用

**Comment by robot-2233** [comment]
目前代码会 憋着带战吼的牌不用 不会用法术 不会交易 不会锻造 不会泰坦 不会发现

所以我个人觉得应该代码里要弄个 Everything fxxk out的策略 只管扔出手牌 然后随从全部打脸 用完所有法力水晶的贪婪策略

**Comment by robot-2233** [comment]
@xjw580

**Comment by robot-2233** [comment]
@H2annibal @xjw580 你们怎么看

**Comment by xjw580** [comment]
> @H2annibal @xjw580 你们怎么看

因为有些战吼打出需要指向或其他操作，可能会卡住下一张牌的打出，法术的话收益不确定，不过也可以添加该策略。
想交易锻造这些复杂的策略需要你们自行编写插件，我只维护软件的运行。

**Comment by robot-2233** [comment]
> > @H2annibal @xjw580 你们怎么看
> 
> 因为有些战吼打出需要指向或其他操作，可能会卡住下一张牌的打出，法术的话收益不确定，不过也可以添加该策略。 想交易锻造这些复杂的策略需要你们自行编写插件，我只维护软件的运行。

可以 我也觉得锻造交易其实不需要 但是围绕战吼随从的逻辑亟待解决 因为好多随从自带战吼 所有战吼牌不能出其实有些难受hhhh

**Comment by robot-2233** [comment]
本人做的py算法那边 其实也有想过怎么设计几个聪明的算法 但是上手发现我还需要学习

**Comment by H2annibal** [comment]
平台能否收集胜率比较好的策略和卡组信息？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bomb-sniffing Pomeranian ***@***.***&gt;
发送时间: 2024年10月17日 17:41
收件人: xjw580/Hearthstone-Script ***@***.***&gt;
抄送: H2annibal ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [xjw580/Hearthstone-Script] 请问各位大佬能否回复几个效率比较高的卡组，多谢啦。 (Issue #31)





 
本人做的py算法那边 其实也有想过怎么设计几个聪明的算法 但是上手发现我还需要学习

**Comment by xjw580** [comment]
> 平台能否收集胜率比较好的策略和卡组信息？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Bomb-sniffing Pomeranian ***@***.***&gt; 发送时间: 2024年10月17日 17:41 收件人: xjw580/Hearthstone-Script ***@***.***&gt; 抄送: H2annibal ***@***.***&gt;, Mention ***@***.***&gt; 主题: Re: [xjw580/Hearthstone-Script] 请问各位大佬能否回复几个效率比较高的卡组，多谢啦。 (Issue #31) 本人做的py算法那边 其实也有想过怎么设计几个聪明的算法 但是上手发现我还需要学习 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

说过了策略要自己写，没对卡牌适配的策略胜率不可能高，有卡组也没用。

**Comment by robot-2233** [comment]
@xjw580 这个也难实现 维护起来工作量也大 确实难

诶对了 能不能加个我方血量少于15而敌方血量大于三十 并且有十个法力水晶就自动投降啊 这种对局应该是尘埃落定了

**Comment by xjw580** [comment]
> @xjw580 这个也难实现 维护起来工作量也大 确实难
> 
> 诶对了 能不能加个我方血量少于15而敌方血量大于三十 并且有十个法力水晶就自动投降啊 这种对局应该是尘埃落定了

策略相关要么自己写插件要么提pr

**Comment by H2annibal** [comment]
基本策略里面，战吼，法术，能不能默认正面收益释放？英雄技能基本都是固定，能不能也在基本策略里配置释放

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zerg ***@***.***&gt;
发送时间: 2024年10月17日 22:19
收件人: xjw580/Hearthstone-Script ***@***.***&gt;
抄送: H2annibal ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [xjw580/Hearthstone-Script] 请问各位大佬能否回复几个效率比较高的卡组，多谢啦。 (Issue #31)





  
@xjw580 这个也难实现 维护起来工作量也大 确实难
 
诶对了 能不能加个我方血量少于15而敌方血量大于三十 并且有十个法力水晶就自动投降啊 这种对局应该是尘埃落定了
  
策略相关要么自己写插件要么提pr
