### ISSUE TITLE
关于投降策略的疑问  经常很久不执行任何操作  然后超时   不好意思不太会用GitHub  貌似创建了一个新的 话题

### ISSUE THREAD

**Issue by LuoShen1512** [xjw580/Hearthstone-Script#37]
关于投降策略的疑问  经常很久不执行任何操作  就是超时  狠狠超时
![image](https://user-images.githubusercontent.com/134152118/376438945-9a68e4f2-65db-4e8c-acfb-79e47f3404e9.png)

**Comment by LuoShen1512** [comment]
![image](https://github.com/user-attachments/assets/69b75109-f48e-4bba-8038-9072759f6a4f)

**Comment by xjw580** [comment]
正常就是创建新的issue。看下前面正常的日志

**Comment by LuoShen1512** [comment]
啥时候会触发投降  像这一把  到第二回合才触发投降
![image](https://github.com/user-attachments/assets/b9a19b09-04e4-454f-b281-d4b19104f1e0)

**Comment by LuoShen1512** [comment]
不好意思  刚才翻日志  想截一局完整的日志   但是突然日志刷新了      一会再看看有没有类似的情况

**Comment by xjw580** [comment]
> 不好意思 刚才翻日志 想截一局完整的日志 但是突然日志刷新了 一会再看看有没有类似的情况

到日志文件里看就行了

**Comment by LuoShen1512** [comment]
像这一局   就花了挺长时间才执行投降操作成功
![image](https://github.com/user-attachments/assets/a789aef6-f3b9-4078-8b72-e52c53f2cf44)
![image](https://github.com/user-attachments/assets/5b323cee-f450-4685-afef-957588ee5ff1)

**Comment by xjw580** [comment]
已经找到问题所在，稍后发布新版本

**Comment by xjw580** [comment]
[v4.0.2-BETA](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.0.2-BETA)中修复

**Comment by LuoShen1512** [comment]
效率也太高了哥
