### ISSUE TITLE
安装了jdk21,启动的时候还是提示低于jdk21 跳去下载安装

### ISSUE THREAD

**Issue by karaner** [xjw580/Hearthstone-Script#39]
![jdk21](https://github.com/user-attachments/assets/ee120a46-2285-4e9f-a7ad-4b622f8c1f36)

**Comment by xjw580** [comment]
看下你java -version的输出

**Comment by karaner** [comment]
我重新重启电脑可以，但是开着炉石，打开软件，卡启动界面了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月15日 11:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xjw580/Hearthstone-Script] 安装了jdk21,启动的时候还是提示低于jdk21 跳去下载安装 (Issue #39) |

看下你java -version的输出

**Comment by xjw580** [comment]
> 我重新重启电脑可以，但是开着炉石，打开软件，卡启动界面了
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年10月15日 11:30 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [xjw580/Hearthstone-Script] 安装了jdk21,启动的时候还是提示低于jdk21 跳去下载安装 (Issue #39) | 看下你java -version的输出 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

直接执行jar包看看输出

**Comment by xjw580** [comment]
> 我运行stop.bat后，重新启动就可以了，但是现在界面是乱码的，这个能调吗？

什么意思

**Comment by karaner** [comment]
> > 我运行stop.bat后，重新启动就可以了，但是现在界面是乱码的，这个能调吗？
> 
> 什么意思

![luanma](https://github.com/user-attachments/assets/4c479c9e-0bab-4310-9316-1b9431ab8aab)
界面是这样的，文字显示都是乱码

**Comment by xjw580** [comment]
直接
```
java -jar 
```
执行看看

**Comment by karaner** [comment]
> 直接
> 
> ```
> java -jar 
> ```
> 
> 执行看看

![luanma](https://github.com/user-attachments/assets/8a5897cd-52b8-40c4-af19-c67d598933b8)
也不行，运行窗口里面的文件也是乱码

**Comment by xjw580** [comment]
> > 直接
> > ```
> > java -jar 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 执行看看
> 
> ![luanma](https://private-user-images.githubusercontent.com/5621973/376486517-8a5897cd-52b8-40c4-af19-c67d598933b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzQ1ODAsIm5iZiI6MTcyODk3NDI4MCwicGF0aCI6Ii81NjIxOTczLzM3NjQ4NjUxNy04YTU4OTdjZC01MmI4LTQwYzQtYWYxOS1jNjdkNTk4OTMzYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMDYzODAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWM4YjE2YmVjNTZlYWNmOGMzNmY2ZGNjN2VkYjIzNTI5NDkzZTk4ODRhYTMyZjQ0YjFlZjY1NGFmMDVkODQzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3RZ4TITeTxe1hIRUzD6pdSpw-FKd84BlUo8yXUXLrg4) 也不行，运行窗口里面的文件也是乱码

 ```
 java -jar -Dfile.encoding=UTF-8
```
再执行看看

**Comment by karaner** [comment]
> > > 直接
> > > ```
> > > java -jar 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 执行看看
> > 
> > 
> > ![luanma](https://private-user-images.githubusercontent.com/5621973/376486517-8a5897cd-52b8-40c4-af19-c67d598933b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzQ1ODAsIm5iZiI6MTcyODk3NDI4MCwicGF0aCI6Ii81NjIxOTczLzM3NjQ4NjUxNy04YTU4OTdjZC01MmI4LTQwYzQtYWYxOS1jNjdkNTk4OTMzYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMDYzODAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWM4YjE2YmVjNTZlYWNmOGMzNmY2ZGNjN2VkYjIzNTI5NDkzZTk4ODRhYTMyZjQ0YjFlZjY1NGFmMDVkODQzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3RZ4TITeTxe1hIRUzD6pdSpw-FKd84BlUo8yXUXLrg4) 也不行，运行窗口里面的文件也是乱码
> 
> ```
> java -jar -Dfile.encoding=UTF-8
> ```
> 
> 再执行看看，（黑窗口里乱码正常，黑窗口里执行chcp65001就不会乱码了）

还是不行
