### ISSUE TITLE
是否可以调整投降的速度

### ISSUE THREAD

**Issue by LuoShen1512** [xjw580/Hearthstone-Script#41]
![image](https://github.com/user-attachments/assets/957daf91-a4de-48b3-80af-f3cc3dffe9e8)
这里应该是调整一般的执行操作的时间吧
我想问如何调整、加长投降操作的时间
因为已经连续投降九十多把了，貌似还没有进入互投区，
还是说是因为投的太快了，对面来不及投降

**Comment by xjw580** [comment]
投降策略是写在插件里的，目前没有插件设置页，也就是说不能自定义调整

**Comment by LuoShen1512** [comment]
好滴好滴  无伤大雅      还是十分感谢大哥的

**Comment by LuoShen1512** [comment]
但是浏览了一下社区什么的  貌似说互投区被官方修复了

**Comment by LuoShen1512** [comment]
辛苦作者大大了
