### ISSUE TITLE
拉去项目运行时 报错

### ISSUE THREAD

**Issue by limcod** [xjw580/Hearthstone-Script#43]
![image](https://github.com/user-attachments/assets/a0d3d58d-8235-45ae-9a6e-eb9e21a16ad1)

报错日志如上  请问需要如何解决

**Comment by limcod** [comment]
是的

**Comment by limcod** [comment]
会不会是我上述原因导致的

**Comment by xjw580** [comment]
> 是的 master分支 我的jdk是22 并且这个有个爆红但是 导包没有效果 ![image](https://private-user-images.githubusercontent.com/69674400/376622677-d39c051e-c6a9-4ff6-84d4-d0a4ba2b1eea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTgxMjgsIm5iZiI6MTcyODk5NzgyOCwicGF0aCI6Ii82OTY3NDQwMC8zNzY2MjI2NzctZDM5YzA1MWUtYzZhOS00ZmY2LTg0ZDQtZDBhNGJhMmIxZWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDEzMTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2OWYyZDhiNDcxMDk4OTdjZGM4ZTlkNDI5YmViNmZkYTYxNDEzMzg0ZTMwNWFlNDk2NmJlMDE2MzE5YzNkMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._i35KO7OdCX7Cl1Zi6NS1hjupm3O8ajovpXMrI5b64o)

刚刚push了，只提交忘push了

**Comment by limcod** [comment]
openjdk  与 graaIVMjdk  会不会有什么影响

**Comment by limcod** [comment]
好的

**Comment by xjw580** [comment]
> openjdk 与 graaIVMjdk 会不会有什么影响

正常来说不会

**Comment by limcod** [comment]
可以了  运行起来  谢谢

**Comment by limcod** [comment]
但是截图部分的爆红依然存在  不过不影响运行
![image](https://github.com/user-attachments/assets/98228b18-5e97-4f57-be95-9b432e9462af)

**Comment by limcod** [comment]
发现了新的问题  在页面的运行按钮点击后  提示注入失败
![image](https://github.com/user-attachments/assets/39ea3084-520d-4777-b39f-3168d558a952)


在其他的issue里面看到有关于检查依赖相关  已检查依赖似乎都存在

**Comment by limcod** [comment]
![image](https://github.com/user-attachments/assets/12abd4fb-8bbc-470a-a0fc-8d3dfb42f5a5)
![image](https://github.com/user-attachments/assets/1119f631-c380-4cc5-b217-71bc9319625e)

**Comment by limcod** [comment]
可是是我用的idea的调试。。。

**Comment by xjw580** [comment]
> 可是是我用的idea的调试。。。

管理员运行IDE

**Comment by limcod** [comment]
好的  谢谢已经可以正常运行
