### ISSUE TITLE
运行程序白屏，程序日记没有报错，鼠标划到对应的区域还是可以点击，只是单纯不显示

### ISSUE THREAD

**Issue by QWEA0** [xjw580/Hearthstone-Script#48]
<img width="656" alt="屏幕截图 2024-10-16 223429" src="https://github.com/user-attachments/assets/68efd338-59b8-41c0-b38a-59c3ef403049">
<img width="738" alt="屏幕截图 2024-10-16 223527" src="https://github.com/user-attachments/assets/a2457eb7-ee4e-4bf9-b064-76136722b0f4">

**Comment by xjw580** [comment]
系统版本，JDK版本是什么

**Comment by QWEA0** [comment]
> 系统版本，JDK版本是什么

![Uploading 屏幕截图 2024-10-16 233445.png…]()

**Comment by QWEA0** [comment]
> 系统版本，JDK版本是什么

<img width="580" alt="屏幕截图 2024-10-16 233703" src="https://github.com/user-attachments/assets/5a982ea5-4f2c-42ac-b6f0-206f53971117">

**Comment by QWEA0** [comment]
<img width="643" alt="屏幕截图 2024-10-16 233839" src="https://github.com/user-attachments/assets/911725e6-9e69-4716-b73c-15d2e9ec5d36">
