### ISSUE TITLE
大佬更新完4.0.4版本后，有没有冻结账号的

### ISSUE THREAD

**Issue by fengzaichuiwo** [xjw580/Hearthstone-Script#49]

**Comment by krin295** [comment]
前面挂了十几天没问题，昨天晚上给封了3天

**Comment by fengzaichuiwo** [comment]
> 前面挂了十几天没问题，昨天晚上给封了3天
脚本有更新到最新版本吗？每天挂多长时间？

**Comment by krin295** [comment]
> > 前面挂了十几天没问题，昨天晚上给封了3天
> > 脚本有更新到最新版本吗？每天挂多长时间？

还没来得及更新就被封了，之前每天休闲挂12-15个小时左右，

**Comment by fengzaichuiwo** [comment]
还挺幸运的，我是刚开服一周挂了三天被封了三天

**Comment by blackcatL0** [comment]
他们检测得到，我觉得甚至暗示过我，但我没理🤣

**Comment by robot-2233** [comment]
@blackcatL0 暗示？怎么暗示到你的啊？

**Comment by yiyuxie98** [comment]
我挂了一天，然后被封了三天哈哈

**Comment by blackcatL0** [comment]
@yiyuxie98 [这里作者给了补丁链接，小号的话可以尝试一下看看](https://github.com/xjw580/Hearthstone-Script/issues/24)
