### ISSUE TITLE
无法使用技能

### ISSUE THREAD

**Issue by niubifengfeng** [xjw580/Hearthstone-Script#51]
1、英雄技能在有费用的时候，能不能自动对英雄释放。这样可以更像真人，减少被举报几率
2、不需要指定目标的通用战吼牌，能不能也加入可以使用，比如战吼：抽一张牌。这类。

**Comment by xjw580** [comment]
1. 基础英雄技能不都适配了么？
2 .哥们，你怎么版本都跟不上? [v4.0.5-BETA](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.0.5-BETA)

**Comment by niubifengfeng** [comment]
![image](https://github.com/user-attachments/assets/e903f10c-7a93-46da-af6c-00c6bbbb8325)
我是4.05了啊，英雄技能还是不用啊

**Comment by niubifengfeng** [comment]
战吼我是没试，之后试下

**Comment by xjw580** [comment]
> ![image](https://private-user-images.githubusercontent.com/167000156/377947846-e903f10c-7a93-46da-af6c-00c6bbbb8325.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNzAzNzYsIm5iZiI6MTcyOTI3MDA3NiwicGF0aCI6Ii8xNjcwMDAxNTYvMzc3OTQ3ODQ2LWU5MDNmMTBjLTdhOTMtNDZkYS1hZjZjLTAwYzZiYmJiODMyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxNjQ3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODMwZDdlYzAyNjEzYmRkNDdiMjA2ZWJhOWQ4OTg1OTkzMzJiODUwMTg2NDBiZDRlNDMwYmU3MGMyNjcyMDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.O3wkmSNBezl--XS88cu2cBQRiuPXc7r8aIkpRvisbdg) 我是4.05了啊，英雄技能还是不用啊，水晶还是满的

我这边初步测试好像没啥问题

**Comment by 123wuzhichen** [comment]
这边基础策略和激进策略也都不会使用技能v4.06

**Comment by xjw580** [comment]
> 这边基础策略和激进策略也都不会使用技能v4.06

所有职业都这样？

**Comment by jh13champion** [comment]
> > 这边基础策略和激进策略也都不会使用技能v4.06
> 
> 所有职业都这样？

我试了术士和猎人都不会用技能，v4.06-DEV

**Comment by yiyuxie98** [comment]
大佬，我用了猎人，确实没用技能，4.0.6

**Comment by yiyuxie98** [comment]
我还试了瞎子也不会用技能，4.05版本

**Comment by JKWTCN** [comment]
萨满技能也不会用。v4.06-DEV

**Comment by robot-2233** [comment]
@xjw580 激进策略还有个小bug 
增益性法术指向随从时会点击到该随从右边一格 导致无法使用增益性法术 eg:使一个随从+2/+3
log如下

**Comment by robot-2233** [comment]
@xjw580 激进策略还有个小bug
增益性法术指向随从时会点击到该随从右边一格 导致无法使用增益性法术 eg:使一个随从+2/+3
log如下
[hs_script.log](https://github.com/user-attachments/files/17483693/hs_script.log)

**Comment by xjw580** [comment]
@robot-2233 @niubifengfeng [v4.0.7-DEV](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.0.7-DEV)中修复了相关问题，你们可以测试下。

**Comment by robot-2233** [comment]
@xjw580 辛苦辛苦 我测试下

**Comment by llsccm** [comment]
@xjw580 4.0.7术士还是不会用技能
激进模式下法术感觉有时候会打出，有时候又会空过
```
2024-10-26 23:33:53.334 [ListenLogPool Thread-2] [War.kt:44] INFO  主游戏-动作
2024-10-26 23:33:53.334 [ListenLogPool Thread-2] [GameTurnPhaseStrategy.kt:25] INFO  我方回合
2024-10-26 23:33:58.335 [OutCard Thread] [DeckStrategyActuator.kt:119] INFO  执行出牌策略
2024-10-26 23:33:58.335 [OutCard Thread] [DeckStrategyActuator.kt:123] INFO  回合开始可用水晶数：9
2024-10-26 23:33:58.335 [OutCard Thread] [HsRadicalDeckStrategy.kt:52] INFO  待出牌：[【entityId:152，entityName:淤泥桶，cardId:WW_044t】, 【entityId:154，entityName:淤泥桶，cardId:WW_044t】, 【entityId:156，entityName:淤泥桶，cardId:WW_044t】]
2024-10-26 23:33:58.335 [OutCard Thread] [DeckStrategyUtil.kt:220] INFO  开始思考清理嘲讽
2024-10-26 23:33:58.335 [OutCard Thread] [DeckStrategyUtil.kt:338] INFO  禁用反演
2024-10-26 23:33:58.336 [OutCard Thread] [DeckStrategyUtil.kt:377] INFO  思考耗时：0ms
2024-10-26 23:33:58.336 [OutCard Thread] [DeckStrategyUtil.kt:70] INFO  权重: -2.147483648E9, 步骤↓
2024-10-26 23:34:00.361 [ListenLogPool Thread-2] [War.kt:44] INFO  主游戏-步骤结束
2024-10-26 23:34:00.364 [ListenLogPool Thread-2] [War.kt:44] INFO  主游戏-清除
2024-10-26 23:34:00.365 [ListenLogPool Thread-2] [War.kt:44] INFO  主游戏-下一步骤
```

**Comment by xjw580** [comment]
> @xjw580 4.0.7术士还是不会用技能
> 激进模式下法术感觉有时候会打出，有时候又会空过
> ```
> 2024-10-26 23:33:53.334 [ListenLogPool Thread-2] [War.kt:44] INFO  主游戏-动作
> 2024-10-26 23:33:53.334 [ListenLogPool Thread-2] [GameTurnPhaseStrategy.kt:25] INFO  我方回合
> 2024-10-26 23:33:58.335 [OutCard Thread] [DeckStrategyActuator.kt:119] INFO  执行出牌策略
> 2024-10-26 23:33:58.335 [OutCard Thread] [DeckStrategyActuator.kt:123] INFO  回合开始可用水晶数：9
> 2024-10-26 23:33:58.335 [OutCard Thread] [HsRadicalDeckStrategy.kt:52] INFO  待出牌：[【entityId:152，entityName:淤泥桶，cardId:WW_044t】, 【entityId:154，entityName:淤泥桶，cardId:WW_044t】, 【entityId:156，entityName:淤泥桶，cardId:WW_044t】]
> 2024-10-26 23:33:58.335 [OutCard Thread] [DeckStrategyUtil.kt:220] INFO  开始思考清理嘲讽
> 2024-10-26 23:33:58.335 [OutCard Thread] [DeckStrategyUtil.kt:338] INFO  禁用反演
> 2024-10-26 23:33:58.336 [OutCard Thread] [DeckStrategyUtil.kt:377] INFO  思考耗时：0ms
> 2024-10-26 23:33:58.336 [OutCard Thread] [DeckStrategyUtil.kt:70] INFO  权重: -2.147483648E9, 步骤↓
> 2024-10-26 23:34:00.361 [ListenLogPool Thread-2] [War.kt:44] INFO  主游戏-步骤结束
> 2024-10-26 23:34:00.364 [ListenLogPool Thread-2] [War.kt:44] INFO  主游戏-清除
> 2024-10-26 23:34:00.365 [ListenLogPool Thread-2] [War.kt:44] INFO  主游戏-下一步骤
> ```
> 
> 还有算斩杀的时机是不是应该提前一点比较好？

其他职业的技能咧？
实际上并没有算斩杀的代码，只有随从选择最佳攻击目标的算法，我把敌方英雄权重拉大了而已，要提前就是把调用随从攻击的算法提前了

**Comment by llsccm** [comment]
我再测测猎人
有时候会出现场攻够了，为了白吃而在解场的情况

**Comment by llsccm** [comment]
@xjw580 猎人技能也不行，甚至出现了满手牌不出牌的问题，可能是更新方式不对？
我已经删除了除配置外所有文件，重新下载4.0.7，再次测试，术士技能依然不会使用

**Comment by JKWTCN** [comment]
我测试了萨满、DK也都不会用技能。v4.07-DEV

**Comment by xjw580** [comment]
> @xjw580 猎人技能也不行，甚至出现了满手牌不出牌的问题，可能是更新方式不对？ 我已经删除了除配置外所有文件，重新下载4.0.7，再次测试，术士技能依然不会使用

<img width="699" alt="image" src="https://github.com/user-attachments/assets/34dd1265-7881-4138-acfe-2839837f6567">
我这猎人技能可以正常使用

**Comment by llsccm** [comment]
感觉好多人都不行，有没有可能是github工作流打包出现问题？
我找个地标测测，看看能不能用地标

**Comment by xjw580** [comment]
> 感觉好多人都不行，有没有可能是github工作流打包出现问题？ 我找个地标测测，看看能不能用地标

插件加载那部分有bug，造成打包运行和IDE运行结果不一样

**Comment by xjw580** [comment]
@llsccm 这次应该是修复了 [v4.0.8-DEV](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.0.8-DEV)

**Comment by llsccm** [comment]
<img width="629" alt="屏幕截图 2024-10-29 210216" src="https://github.com/user-attachments/assets/227af2a3-9b7e-48c3-967d-bce2bfa71abd">
等别人测测看吧...

**Comment by niubifengfeng** [comment]
号被封了……

**Comment by jh13champion** [comment]
> <img alt="屏幕截图 2024-10-29 210216" width="629" src="https://private-user-images.githubusercontent.com/48448919/381133307-227af2a3-9b7e-48c3-967d-bce2bfa71abd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTM1MDMsIm5iZiI6MTczMDI5MzIwMywicGF0aCI6Ii80ODQ0ODkxOS8zODExMzMzMDctMjI3YWYyYTMtOWI3ZS00OGMzLTk2N2QtYmNlMmJmYTcxYWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDEzMDAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNTgyZWNmYTIyNDVkMDIxOGJmYWY1MmNmOWMwZmI1MTgxNDgwODU3MzY3NmQ5ZWFlODYwMDY2NDNlYjNjMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ces9rxcJy4KJIMl2NQKYEsSKn-xHR-B4QrfuOwZIxHA"> 等别人测测看吧...

技能用的没有那么积极，但是某些回合还是会用的

**Comment by jh13champion** [comment]
技能不会用得很积极，某些回合才会用

**Comment by xjw580** [comment]
只有使用原皮才能正常使用技能，因为不同皮肤下技能的cardId不相同，而我只适配了原皮的技能
