### ISSUE TITLE
推荐一套无战吼无法术的鱼人卡组，有一定强度，减少被举报的概率；还有，在第一回合有概率烧绳，之后的回合正常，未知原因

### ISSUE THREAD

**Issue by xianji123** [xjw580/Hearthstone-Script#52]
### 鱼人
# 职业：猎人
# 模式：狂野模式
#
# 2x (1) 人潮冲浪者
# 2x (1) 暗鳞先知
# 1x (1) 进化融合怪
# 2x (1) 错误产物
# 2x (1) 鱼人招潮者
# 2x (1) 鱼人木乃伊
# 2x (1) 鱼人袭击者
# 2x (2) 交际鱼人
# 2x (2) 红鳃锋颚战士
# 2x (2) 蓝鳃战士
# 2x (3) 团队领袖
# 2x (3) 大作战狂热玩家
# 2x (3) 扮装选手
# 1x (3) 捣蛋林精
# 2x (3) 鱼人领军
# 2x (5) 湾鳍健身鱼人
# 
AAEBAR8Cx7AGltMGDr8B/gPjBaGfBKugBLq0BO7TBJWqBdPQBZGOBtSeBom4Buy8BpO/BgAA
# 
# 想要使用这副套牌，请先复制到剪贴板，然后在游戏中点击“新套牌”进行粘贴。

**Comment by xianji123** [comment]
/# AAEBAR8Cx7AGltMGDr8B/gPjBaGfBKugBLq0BO7TBJWqBdPQBZGOBtSeBom4Buy8BpO/BgAA#

**Comment by robot-2233** [comment]
似乎是狂野卡组 可以使用吗？
我的版本是4.0.0.3

**Comment by John-bai-Smith** [comment]
有一定强度=能赢全靠连输之后匹配到秒投的

**Comment by John-bai-Smith** [comment]
不过感觉是能降低被举报概率，如果被脚本打死了，那肯定要举报的，但如果把脚本打死了，那心情好可能就不举报了
