### ISSUE TITLE
有没有在控制界面加入 可以根据输入的名称选择使用的卡组的功能的计划

### ISSUE THREAD

**Issue by limcod** [xjw580/Hearthstone-Script#53]

**Comment by xjw580** [comment]
应用场景是什么

**Comment by limcod** [comment]
现在是只能在开始匹配的时候手动去选择一套 不然默认是第一个？

**Comment by xjw580** [comment]
> 现在是只能在开始匹配的时候手动去选择一套 不然默认是第一个？
> 

你说游戏里选择卡组的位置？

**Comment by limcod** [comment]
我是说 现在是怎么选择的卡组  是直接选择使用第一个吗

**Comment by limcod** [comment]
![image](https://github.com/user-attachments/assets/18744e77-86ba-4c7f-8ed2-71325f8ef148)
就是这里的名称 他是怎么去选择的卡组  卡组名也要叫做苗头策略   还是说只能去选第一个卡组位置的卡组

**Comment by xjw580** [comment]
> ![image](https://github.com/user-attachments/assets/18744e77-86ba-4c7f-8ed2-71325f8ef148)
> 就是这里的名称 他是怎么去选择的卡组  卡组名也要叫做苗头策略   还是说只能去选第一个卡组位置的卡组

第一个位置
