### ISSUE TITLE
发生很多次了，挂久了，卡组满费，什么牌都不出，就等烧绳子

### ISSUE THREAD

**Issue by niubifengfeng** [xjw580/Hearthstone-Script#55]
![image](https://github.com/user-attachments/assets/723e2e9e-efa0-4704-be40-2795b7dbf326)

**Comment by niubifengfeng** [comment]
注意看，什么牌都没出，自动点了结束回合，结束按钮还在翻转过程截图了

**Comment by xjw580** [comment]
日志

**Comment by niubifengfeng** [comment]
好，下次发现了截日志，但是昨天挂了很久，又没出现
