### ISSUE TITLE
激进模式能调成地标自动使用吗

### ISSUE THREAD

**Issue by yiyuxie98** [xjw580/Hearthstone-Script#58]
大佬，请问激进模式里面地标可以自动使用吗，感觉海盗瞎还是需要地标召海盗的

**Comment by xjw580** [comment]
> 大佬，请问激进模式里面地标可以自动使用吗，感觉海盗瞎还是需要地标召海盗的

不能

**Comment by xjw580** [comment]
[v4.0.7-DEV](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.0.7-DEV)已支持使用非指向性地标

**Comment by yiyuxie98** [comment]
感谢大佬
