### ISSUE TITLE
测试版4.0.6会出现运行几个小时后找不到窗口句柄的问题

### ISSUE THREAD

**Issue by jiuxiajingfan** [xjw580/Hearthstone-Script#60]
运行版本 ： dev-4.0.6
运行环境： windows 
日志提示 ： 炉石传说已在运行，但未找到窗口句柄

**Comment by xjw580** [comment]
所以那个时候游戏还在没在运行？

**Comment by Kmaj1st** [comment]
我有同样的故障，游戏是运行状态的，但是变成了非全屏窗口。

**Comment by jiuxiajingfan** [comment]
游戏处于运行状态 多发生于打完一局选牌界面  游戏窗口大小为114*？忘记了 是炉石兄弟的最小化尺寸



---- 回复的原邮件 ----
| 发件人 | Ziqi ***@***.***> |
| 日期 | 2024年10月25日 23:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xjw580/Hearthstone-Script] 测试版4.0.6会出现运行几个小时后找不到窗口句柄的问题 (Issue #60) |

我有同样的故障，游戏是运行状态的，但是变成了非全屏窗口。

**Comment by xjw580** [comment]
> 游戏处于运行状态 多发生于打完一局选牌界面  游戏窗口大小为114*？忘记了 是炉石兄弟的最小化尺寸
> 
> 
> 
> ---- 回复的原邮件 ----
> | 发件人 | Ziqi ***@***.***> |
> | 日期 | 2024年10月25日 23:01 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.***>***@***.***> |
> | 主题 | Re: [xjw580/Hearthstone-Script] 测试版4.0.6会出现运行几个小时后找不到窗口句柄的问题 (Issue #60) |
> 
> 我有同样的故障，游戏是运行状态的，但是变成了非全屏窗口。
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

软件里没有改窗口大小的代码

**Comment by jiuxiajingfan** [comment]
> > 游戏处于运行状态 多发生于打完一局选牌界面  游戏窗口大小为114*？忘记了 是炉石兄弟的最小化尺寸
> > ---- 回复的原邮件 ----
> > | 发件人 | Ziqi _**@**_._**> |
> > | 日期 | 2024年10月25日 23:01 |
> > | 收件人 | _**@**_.**_> |
> > | 抄送至 | _**@**_._**>**_@_**.**_> |
> > | 主题 | Re: [xjw580/Hearthstone-Script] 测试版4.0.6会出现运行几个小时后找不到窗口句柄的问题 (Issue #60) |
> > 我有同样的故障，游戏是运行状态的，但是变成了非全屏窗口。
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 软件里没有改窗口大小的代码

好的 我在物理实体机再试试看能否复现 之前是在虚拟机中由于性能问题分辨率弄了窗口最小化

**Comment by Kmaj1st** [comment]
在我这边会出现这个错误似乎是因为软件需要重启游戏却失败了，详细日志如下：
```
2024-10-25 22:01:27.011 [ListenLogPool Thread-3] [GameUtil.kt:357] INFO  点掉游戏结束结算页面
2024-10-25 22:01:27.011 [ListenLogPool Thread-3] [WarEx.kt:105] INFO  已重置游戏状态
2024-10-25 22:01:27.011 [ListenLogPool Thread-3] [AbstractPhaseStrategy.kt:126] INFO  游戏结束阶段 -> 结束
2024-10-25 22:01:39.669 [ListenLogPool Thread-0] [AbstractModeStrategy.kt:25] INFO  切換到【传统对战界面】
2024-10-25 22:01:39.671 [ListenLogPool Thread-0] [TournamentModeStrategy.kt:116] INFO  power.log即将达到51200KB，准备重启游戏
2024-10-25 22:01:39.691 [CorePool Thread-1] [Mode.kt:29] INFO  已重置模式状态
2024-10-25 22:01:39.692 [CorePool Thread-1] [Core.kt:39] INFO  当前处于【停止】状态
2024-10-25 22:01:39.692 [CorePool Thread-1] [GameUtil.kt:438] INFO  炉石传说不在运行
2024-10-25 22:01:39.692 [CorePool Thread-1] [Core.kt:86] INFO  游戏重启中……
2024-10-25 22:01:39.696 [CorePool Thread-1] [Core.kt:46] INFO  当前处于【运行】状态
2024-10-25 22:01:39.696 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【ClearStarter】
2024-10-25 22:01:39.696 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【PlatformStarter】
2024-10-25 22:01:40.022 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【LoginPlatformStarter】
2024-10-25 22:01:40.307 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【GameStarter】
2024-10-25 22:01:40.308 [CorePool Thread-0] [GameStarter.kt:34] INFO  开始检查炉石传说
2024-10-25 22:01:40.686 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
2024-10-25 22:01:42.692 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
2024-10-25 22:01:44.698 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
2024-10-25 22:01:46.688 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
2024-10-25 22:01:48.711 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
2024-10-25 22:01:50.684 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
2024-10-25 22:01:52.674 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
2024-10-25 22:01:54.685 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
2024-10-25 22:01:56.410 [LaunchProgramPool Thread-1] [GameStarter.kt:44] INFO  更改炉石传说启动方式
2024-10-25 22:01:56.740 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
```
值得一提的是，我暂停脚本的运行之后再恢复运行也会导致这种情况的发生。也就是说，每当我在暂停脚本后需要重新运行脚本，我都要手动关闭旧的游戏窗口。

**Comment by Kmaj1st** [comment]
> 在我这边会出现这个错误似乎是因为软件需要重启游戏却失败了，详细日志如下：
> 
> ```
> 2024-10-25 22:01:27.011 [ListenLogPool Thread-3] [GameUtil.kt:357] INFO  点掉游戏结束结算页面
> 2024-10-25 22:01:27.011 [ListenLogPool Thread-3] [WarEx.kt:105] INFO  已重置游戏状态
> 2024-10-25 22:01:27.011 [ListenLogPool Thread-3] [AbstractPhaseStrategy.kt:126] INFO  游戏结束阶段 -> 结束
> 2024-10-25 22:01:39.669 [ListenLogPool Thread-0] [AbstractModeStrategy.kt:25] INFO  切換到【传统对战界面】
> 2024-10-25 22:01:39.671 [ListenLogPool Thread-0] [TournamentModeStrategy.kt:116] INFO  power.log即将达到51200KB，准备重启游戏
> 2024-10-25 22:01:39.691 [CorePool Thread-1] [Mode.kt:29] INFO  已重置模式状态
> 2024-10-25 22:01:39.692 [CorePool Thread-1] [Core.kt:39] INFO  当前处于【停止】状态
> 2024-10-25 22:01:39.692 [CorePool Thread-1] [GameUtil.kt:438] INFO  炉石传说不在运行
> 2024-10-25 22:01:39.692 [CorePool Thread-1] [Core.kt:86] INFO  游戏重启中……
> 2024-10-25 22:01:39.696 [CorePool Thread-1] [Core.kt:46] INFO  当前处于【运行】状态
> 2024-10-25 22:01:39.696 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【ClearStarter】
> 2024-10-25 22:01:39.696 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【PlatformStarter】
> 2024-10-25 22:01:40.022 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【LoginPlatformStarter】
> 2024-10-25 22:01:40.307 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【GameStarter】
> 2024-10-25 22:01:40.308 [CorePool Thread-0] [GameStarter.kt:34] INFO  开始检查炉石传说
> 2024-10-25 22:01:40.686 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> 2024-10-25 22:01:42.692 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> 2024-10-25 22:01:44.698 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> 2024-10-25 22:01:46.688 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> 2024-10-25 22:01:48.711 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> 2024-10-25 22:01:50.684 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> 2024-10-25 22:01:52.674 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> 2024-10-25 22:01:54.685 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> 2024-10-25 22:01:56.410 [LaunchProgramPool Thread-1] [GameStarter.kt:44] INFO  更改炉石传说启动方式
> 2024-10-25 22:01:56.740 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> ```
> 
> 值得一提的是，我暂停脚本之后再恢复运行也会导致这种情况的发生。也就是说，每当我在暂停脚本后需要重新运行脚本，我都要手动关闭旧的游戏窗口。


在我的运行环境，导致这个问题发生的原因是：
1. 系统使用的不是中文语言，
2. 游戏使用了中文语言。

由于以上两点，hs-script在第一次尝试获取炉石传说游戏窗口时将炉石传说游戏窗口标题从"Hearthstone"重命名为"????"（既"炉石传说"，但看不懂中文版），原因未知。在重启时因为无法找到符合GAME_CN_NAME或GAME_US_NAME标题的窗口进而无法重启游戏，所以发生了上述的错误。

亲测有效的解决方案时：把游戏语言切换为英文

**Comment by xjw580** [comment]
> > 在我这边会出现这个错误似乎是因为软件需要重启游戏却失败了，详细日志如下：
> > ```
> > 2024-10-25 22:01:27.011 [ListenLogPool Thread-3] [GameUtil.kt:357] INFO  点掉游戏结束结算页面
> > 2024-10-25 22:01:27.011 [ListenLogPool Thread-3] [WarEx.kt:105] INFO  已重置游戏状态
> > 2024-10-25 22:01:27.011 [ListenLogPool Thread-3] [AbstractPhaseStrategy.kt:126] INFO  游戏结束阶段 -> 结束
> > 2024-10-25 22:01:39.669 [ListenLogPool Thread-0] [AbstractModeStrategy.kt:25] INFO  切換到【传统对战界面】
> > 2024-10-25 22:01:39.671 [ListenLogPool Thread-0] [TournamentModeStrategy.kt:116] INFO  power.log即将达到51200KB，准备重启游戏
> > 2024-10-25 22:01:39.691 [CorePool Thread-1] [Mode.kt:29] INFO  已重置模式状态
> > 2024-10-25 22:01:39.692 [CorePool Thread-1] [Core.kt:39] INFO  当前处于【停止】状态
> > 2024-10-25 22:01:39.692 [CorePool Thread-1] [GameUtil.kt:438] INFO  炉石传说不在运行
> > 2024-10-25 22:01:39.692 [CorePool Thread-1] [Core.kt:86] INFO  游戏重启中……
> > 2024-10-25 22:01:39.696 [CorePool Thread-1] [Core.kt:46] INFO  当前处于【运行】状态
> > 2024-10-25 22:01:39.696 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【ClearStarter】
> > 2024-10-25 22:01:39.696 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【PlatformStarter】
> > 2024-10-25 22:01:40.022 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【LoginPlatformStarter】
> > 2024-10-25 22:01:40.307 [CorePool Thread-0] [AbstractStarter.kt:24] INFO  执行【GameStarter】
> > 2024-10-25 22:01:40.308 [CorePool Thread-0] [GameStarter.kt:34] INFO  开始检查炉石传说
> > 2024-10-25 22:01:40.686 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> > 2024-10-25 22:01:42.692 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> > 2024-10-25 22:01:44.698 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> > 2024-10-25 22:01:46.688 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> > 2024-10-25 22:01:48.711 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> > 2024-10-25 22:01:50.684 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> > 2024-10-25 22:01:52.674 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> > 2024-10-25 22:01:54.685 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> > 2024-10-25 22:01:56.410 [LaunchProgramPool Thread-1] [GameStarter.kt:44] INFO  更改炉石传说启动方式
> > 2024-10-25 22:01:56.740 [LaunchProgramPool Thread-1] [GameStarter.kt:62] INFO  炉石传说已在运行，但未找到对应窗口句柄
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 值得一提的是，我暂停脚本之后再恢复运行也会导致这种情况的发生。也就是说，每当我在暂停脚本后需要重新运行脚本，我都要手动关闭旧的游戏窗口。
> 
> 在我的运行环境中导致这个问题发生的原因是：
> 
> 1. 系统使用的不是中文语言，
> 2. 游戏使用了中文语言。
> 
> 由于以上两点，hs-script在第一次尝试获取炉石传说游戏窗口时将炉石传说游戏窗口标题从"Hearthstone"重命名为"????"（既"炉石传说"，但看不懂中文版），原因未知。在重启时因为无法找到符合GAME_CN_NAME或GAME_US_NAME标题的窗口进而无法重启游戏，所以发生了上述的错误。
> 
> （在将GAME_LOG_LIMIT设置为100的环境下测试时）亲测有效的解决方案是：把游戏语言切换为英文

你那系统的默认编码是什么？
游戏在简中下窗口标题是炉石传说，非简中都是Hearthstone

**Comment by Kmaj1st** [comment]
> 你那系统的默认编码是什么？ 游戏在简中下窗口标题是炉石传说，非简中都是Hearthstone

我似乎找到了更好的解决方案：
将"Language for non-Unicode programs"修改为"Chinese(Simplified, China)"之后，窗口就会正常重命名为“炉石传说”了，Heartshtone-script也可以正常运作。

**回答你的问题，以下是详细记录**：
我对编码这个概念还不太熟悉，所以都是通过GUI操作的，可能会遗漏细节。
在"Language & Region"里，"Windows display language"是"English(Netherlands)"，"Country & region"是"Netherlands"。
在"Language for non-Unicode programs"是"English (US)"。

![屏幕截图 2024-10-28 111038](https://github.com/user-attachments/assets/498d7dbc-725e-4aa1-a640-6f05bcc0047a)
在勾选“Beta: Use Unicode UTF-8 for worldwide language support“时，窗口会改名为“炉”。在不勾选的情况下窗口会改名为“????”。
将"Language for non-Unicode programs"修改为"Chinese(Simplified, China)"之后，窗口就会正常重命名为“炉石传说”了，Heartshtone-script也可以正常运作。在cmd输入chcp返回的是“Active code page: 936”。（使用的依然是上述的语言和地区，不需要勾选“Beta: Use Unicode UTF-8 for worldwide language support“）

我想整个问题的过程就是：
1. 开始的窗口标题都是Hearthstone
2. 游戏初始化时依照设置中的语言选项对标题进行本地化重命名
3. 重命名途中遇到了编码错误，导致窗口标题被重命名为乱码
4. Hearthstone-script无法使用预先定义的字符串通过标题找到游戏窗口
5. fail

也许我们应该通过Hearthstone.exe来寻找游戏窗口，而不是游戏窗口标题。

**Comment by xjw580** [comment]
[v4.0.8-DEV](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.0.8-DEV)已修改查找方式
