### ISSUE TITLE
反复弹出不满足最低jdk版本21

### ISSUE THREAD

**Issue by huanghaiji666666** [xjw580/Hearthstone-Script#63]
反复下载JDK21加上重启电脑 运行hs-script.exe 会弹出不满足最低jdk版本21

**Comment by xjw580** [comment]
那你装了jdk21没？cmd窗口运行java -version我瞅瞅

**Comment by huanghaiji666666** [comment]
![Uploading Snipaste_2024-10-29_19-17-31.png…]()

**Comment by huanghaiji666666** [comment]
安装过了
'java' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
是要手动加环境变量吗

**Comment by xjw580** [comment]
> 安装过了 'java' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 是要手动加环境变量吗

没配环境变量

**Comment by huanghaiji666666** [comment]
加完bin就好了 不知道为什么jdk-21_windows-x64_bin.exe不会自己配置变量 管理员安装的
