### ISSUE TITLE
小白一枚，请教下怎么更新到4.0.4之后的版本？

### ISSUE THREAD

**Issue by lzcw0706** [xjw580/Hearthstone-Script#66]
小白一枚，请教下怎么更新到4.0.4之后的版本？目前使用的4.0.3整合的那个patch包，想使用激进和投降策略，好像只有之后的版本。但是之后的beta和dev包都是jar的，想咨询下怎么手工更新进去？谢谢

**Comment by xjw580** [comment]
[参阅](https://github.com/xjw580/Hearthstone-Script/#%E4%BD%BF%E7%94%A8%E6%AD%A5%E9%AA%A4)
