### ISSUE TITLE
4.0.8版本在老旧设备上拖动鼠标速度会很慢

### ISSUE THREAD

**Issue by lzcw0706** [xjw580/Hearthstone-Script#67]
4.0.8版本在老旧设备上拖动鼠标速度会很慢（E3，4G内存），而4.0.3版本则比较正常。（其它配置较高的pc上也正常
然后在设置里 调高鼠标移动的间隔 完全没效果。

**Comment by xjw580** [comment]
后续版本减少了鼠标每次移动的距离，减少每次移动的停顿，让鼠标移动更加连续，简单来讲就是采样提高了。

**Comment by lzcw0706** [comment]
这个能优化 或者做成设置修改的么？


> 后续版本减少了鼠标每次移动的距离，减少每次移动的停顿，让鼠标移动更加连续，简单来讲就是采样提高了。
