### ISSUE TITLE
脚本好像会点进乱斗模式后误触消耗通票

### ISSUE THREAD

**Issue by ido114** [xjw580/Hearthstone-Script#69]
昨天点进乱斗模式后发现开启了一局还没有组套牌的乱斗，看了一下通票也确实少了两张，但是自己没有开过乱斗的印象，送的一次也前几天就打完了，今天看见脚本开启状态下游戏卡在乱斗模式买票界面不动，怀疑可能是脚本误触了买票？

**Comment by xjw580** [comment]
因为现在乱斗那个消耗通票的按钮和广告的按钮位置差不多，所以有概率点到

**Comment by xjw580** [comment]
[v4.0.9-DEV](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.0.9-DEV)已优化
