### ISSUE TITLE
反馈问题

### ISSUE THREAD

**Issue by gwh6662** [xjw580/Hearthstone-Script#7]
[hs_script.log](https://github.com/xjw580/Hearthstone-Script/files/15158736/hs_script.log)
1.最新版本依然无法正常识别雷诺战吼，会在场上有一个随从的情况下重复试图使用铺场法术。
2.结束回合前，有时候会不停无视对面表情导致烧绳。
3.随从拖动攻击时能否加快一点速度。
4.策略有许多问题，比如10费使用驻锚图腾后，手上一堆减价后的0费图腾不用，直接结束回合。有时候手上的幸运币一直不用。
以上问题基本是4.29 23点到24点的时候打了几把观察到的，后面去睡觉了。

**Comment by xjw580** [comment]
图腾团聚将在下个开发版修复；下个开发版将允许设置间隔时间、拖动速度（时间过短或速度过快可能会因为某些卡牌动画过长导致一些新的问题）；策略问题目前不做优化，将在国服正式回归后重写逻辑。

**Comment by gwh6662** [comment]
好的，大佬辛苦了

**Comment by xjw580** [comment]
v3.2.6.1-DEV已经发布
