### ISSUE TITLE
10张手牌不出牌。

### ISSUE THREAD

**Issue by YonghengSun1997** [xjw580/Hearthstone-Script#70]
是不是判断满场不出牌的逻辑用在手牌上了。版本4.0.8-DEV, 一旦己方10张手牌，摇技能结束回合，不出牌。

**Comment by xjw580** [comment]
日志

**Comment by YonghengSun1997** [comment]
![Screenshot 2024-11-03 185044](https://github.com/user-attachments/assets/3cf509b0-0419-4116-a10e-06b54f5fc22e)
