### ISSUE TITLE
给作者大大提一个小建议，后续可以考虑一下搞个卡牌白名单组，可以在留牌和出牌时给予一定的优先级，这样可以挺高不少胜率。也可以大大降低自建套牌策略编写的成本。

### ISSUE THREAD

**Issue by sunchina2001** [xjw580/Hearthstone-Script#71]

**Comment by xjw580** [comment]
[v4.1.3-BETA](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.1.3-BETA)已添加

**Comment by sunchina2001** [comment]
十分荣幸作者大大能接受我的这个提议，还想请问一下，这个weight的格式该如何编写，有文档吗

**Comment by sunchina2001** [comment]
十分荣幸作者大大能接受我的这个提议，还想请问一下，这个weight文档内容的格式是什么样子的，有文档可以参考吗

**Comment by xjw580** [comment]
> 十分荣幸作者大大能接受我的这个提议，还想请问一下，这个weight文档内容的格式是什么样子的，有文档可以参考吗

普通的json格式，你在权重设置页里往右边的表格添加数据就能在根目录下的config目录看见card.weight文件了

**Comment by sunchina2001** [comment]
![screenshot-1731570009138](https://github.com/user-attachments/assets/9d2a8204-77e4-41e6-b302-96485c9050b5)
因为权重设置页面全是空白，我是想自行编写weight文档导入，想了解weight文档中[ ]内填入什么，想知道一下具体格式，还有想请教一下，如果多个卡牌，如何分隔，在一个括号内进行还是直接另起括号分行，还望大佬给出一个范例

**Comment by xjw580** [comment]
![doc](https://github.com/user-attachments/assets/cda688e1-0ec8-4658-ad96-40e54f5810d5)

**Comment by YonghengSun1997** [comment]
请问，如果设置了对手套牌中的卡牌权重，会影响打牌时的解场优先级吗？

**Comment by xjw580** [comment]
> 请问，如果设置了对手套牌中的卡牌权重，会影响打牌时的解场优先级吗？

会

**Comment by xjw580** [comment]
> 请问，如果设置了对手套牌中的卡牌权重，会影响打牌时的解场优先级吗？

参考
https://github.com/xjw580/Hearthstone-Script/blob/master/Hearthstone-Script-Base-Deck%2Fsrc%2Fmain%2Fkotlin%2Fclub%2Fxiaojiawei%2Futil%2FDeckStrategyUtil.kt#L132-L156
