### ISSUE TITLE
点击运行之后没有反应

### ISSUE THREAD

**Issue by qazwhy123** [xjw580/Hearthstone-Script#72]
第一次打开时提示下载jdk-21，下载安装完成后重启电脑，再次打开，没有反应。
系统是win11，在win10下运行似乎也是同样的情况。

尝试过以下方法：
重新安装了c++运行库
管理员权限运行
关闭杀毒软件重新下载
打开windows事件查看器，没有找到对应事件
使用cmd命令行运行，没有报错，也没有反应

**Comment by xjw580** [comment]
#63

**Comment by xjw580** [comment]
#62

**Comment by qazwhy123** [comment]
下载[hs-script_v4.0.8-DEV.zip]解决了，感谢

**Comment by evenfromafar** [comment]
连着两个github.com检查最新版异常，查看脚本日志获取详细错误信息&连着三个未适配LUCKY_DRAW什么情况
