### ISSUE TITLE
请问版本更新后无法启动唤起游戏是什么情况

### ISSUE THREAD

**Issue by AsukaSaki** [xjw580/Hearthstone-Script#74]
更新完版本后就没反映了，重新打开只能打开战网，游戏都不带启动的，我自己点进游戏也是不执行操作。。log如下，然后就没然后了。。（然后我下载了上一个版本的，发现进去后还是这样，这就很奇怪了。运行库都好好的，也是管理员运行，杀毒是关闭着的，java都重装了一遍，还是依旧，不知是什么情况）
logs：

[hs_script.log](https://github.com/user-attachments/files/17645420/hs_script.log)

**Comment by John-bai-Smith** [comment]
遇到了同样的问题，4.0.9版本还能正常运行

**Comment by xjw580** [comment]
重新下载本软件即可
