### ISSUE TITLE
狂野卡组分享-鱼人萨-激进策略-90场-34.4%胜率

### ISSUE THREAD

**Issue by John-bai-Smith** [xjw580/Hearthstone-Script#77]
### 鱼人萨
# 职业：萨满祭司
# 模式：狂野模式
#
# 2x (1) 人潮冲浪者
# 2x (1) 水宝宝鱼人
# 2x (1) 进化融合怪
# 1x (2) 交际鱼人
# 2x (2) 冰钓术
# 2x (2) 甜水鱼人佣兵
# 1x (2) 螃蟹骑士
# 1x (3) 寒光智者
# 2x (3) 小丑鱼
# 2x (3) 机械动物管理员
# 1x (3) 湍流元素特布勒斯
# 1x (3) 食人鱼偷猎者
# 2x (3) 鱼人领军
# 2x (3) 鱼勇可贾
# 1x (4) 老瞎眼
# 2x (5) 鳄鱼人掠夺者
# 1x (7) 吞噬者穆坦努斯
# 1x (0) 奇利亚斯豪华版3000型
#   1x (0) 奇利亚斯豪华版3000型
#   1x (3) 输能模块
#   1x (4) 计数模块
# 2x (7) 鱼人恩典
# 
AAEBAdrGBAjgBfgHkeQDpu8D4rUEkY4Gx6QGreEGC78Xn7cCi84Ck+gD3ewD1bIExc4E7tME09AF0dAGltMGAAED87MGx6QG9rMGx6QG6N4Gx6QGAAA=
# 
# 想要使用这副套牌，请先复制到剪贴板，然后在游戏中点击“新套牌”进行粘贴。

如果有缺卡自己随便换

**Comment by WinKevin66** [comment]
唔唔，新玩家表示好多没有的，哭死

**Comment by John-bai-Smith** [comment]
补充，晚上22：00到7：00，在青铜分段对局中，竟然打出了70场53%胜率的好成绩
