### ISSUE TITLE
脚本使用卡牌的动作缓慢，拿起卡牌后会缓慢得拖向战场

### ISSUE THREAD

**Issue by Chino13ab** [xjw580/Hearthstone-Script#79]
新版本更新后我发现，貌似是在电脑开机第一次运行脚本时是正常的，一旦暂停重新开始就会出现缓慢拖牌的现象。
今天还有一次是在我正常运行脚本后，切出去关闭了炉石的声音，回来后就发现脚本变成了缓慢拖牌的情况
脚本日志如下
[hs_script.log](https://github.com/user-attachments/files/17658793/hs_script.log)
多次尝试过修改操作间隔和移动速度，但并没有起到作用
没有录制具体的问题的视频，如果您需要我会去录制一份

**Comment by xjw580** [comment]
重启软件和游戏也一样吗

**Comment by xjw580** [comment]
cpu型号是什么

**Comment by Chino13ab** [comment]
> cpu型号是什么

![image](https://github.com/user-attachments/assets/6ce39067-c3b6-4c53-841e-0f97f5a5a701)

**Comment by xjw580** [comment]
[system.zip](https://github.com/user-attachments/files/17658927/system.zip)
把zip里的dll替换软件根目录/lib/dll下的同名文件，然后再试试看

**Comment by Chino13ab** [comment]
> [system.zip](https://github.com/user-attachments/files/17658927/system.zip) 把zip里的dll替换软件根目录/lib/dll下的同名文件，然后再试试看

感谢，刚刚测试了两次，暂时没有出现之前的问题了

**Comment by xiaohajiayou** [comment]
你好，我也遇到了这个情况。目前测试内容：通过ide和运行exe的方式，启动脚本进入对局，暂停后再开始，触发对局不完整投降。然后我再点击暂停，手动出牌、攻击都会有明显卡顿（稳定复现）。然后在同一个对局中，直接在ide中断脚本运行后，恢复正常。我录制了卡顿的视频，如果有需要的话。
[Uploading hs_script.log…]()

**Comment by xiaohajiayou** [comment]
你好，我也遇到了这个问题。我测试通过ide运行脚本，进入对局之后点击暂停，然后人工出牌、攻击，都有明显卡顿。然而直接中断脚本运行，卡顿立即消失。我录制了点击暂停后出现卡顿，关闭脚本运行立即恢复的视频，如果需要的话。
[ hs_script.log…]()

**Comment by xjw580** [comment]
> 你好，我也遇到了这个问题。我测试通过ide运行脚本，进入对局之后点击暂停，然后人工出牌、攻击，都有明显卡顿。然而直接中断脚本运行，卡顿立即消失。我录制了点击暂停后出现卡顿，关闭脚本运行立即恢复的视频，如果需要的话。
> [hs_script.log](https://github.com/user-attachments/files/17691902/hs_script.log)
> 

你视频里的操作都是在暂停软件后进行的？

**Comment by xiaohajiayou** [comment]
是的，一开始的时候点击了暂停，然后全部是在暂停之后进行的。ide关闭脚本之后，卡顿消失。

**Comment by xjw580** [comment]
> 是的，一开始的时候点击了暂停，然后全部是在暂停之后进行的。ide关闭脚本之后，卡顿消失。

[adcb8066f54b4e72e3e45231d16421eedc0d0dd4](https://github.com/xjw580/Hearthstone-Script/commit/adcb8066f54b4e72e3e45231d16421eedc0d0dd4)已修复

**Comment by xjw580** [comment]
[v4.1.2-DEV](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.1.2-DEV)已修复
