### ISSUE TITLE
小bug，任务弹窗点击

### ISSUE THREAD

**Issue by bailan999** [xjw580/Hearthstone-Script#8]
1.启动游戏后自动点击弹窗广告等 有没有点击到的弹窗会一直卡住  ，下方图片内这个弹窗就点击不到 会一直卡住，
桌面2K分辨率 游戏是窗口化，我改成全屏后也没点掉，  不知道是否是2K的原因 还是就是默认的点击没有覆盖这个范围，这个不点掉重新上游戏还会在
![QQ图片20240521061522](https://github.com/xjw580/Hearthstone-Script/assets/147543947/f6b81139-782d-4182-acbf-3bdf4b2c5ad0)

2.核心骑士卡组是29张卡，焦油是1张， 应该是少了一张焦油吧，然后卡组默认是选择的狂野模式创建的 不是标准卡组 需要自己转换一下

3.这个不是BUG----切换模式和卡组时 日志下方不会变，  启动脚本时之前选择的是偶数萨，   日志下方显示的就是偶数萨的卡组码， 切换核心骑后，日志内下方卡组代码仍然显示偶数萨，但是会正常自动复制卡组

**Comment by bailan999** [comment]
[Uploading hs_script.log…]()

**Comment by xjw580** [comment]
1. 这个弹窗没做适配，因为这个按钮的位置在我的收藏按钮的上方，我没法判断是否有弹窗，只能默认当做有，所以每次到主页都需要点击该位置，但如果没有弹窗，会点进我的收藏里。
2. 核心骑确实少了一张卡，为什么用狂野套牌？因为核心牌每年都换，直接用狂野套牌可以避免更新套牌
3. 启动后更改套牌不会打印卡组代码，只会自动复制到剪切板并打印切换套牌日志；下个版本可以增加打印

**Comment by bailan999** [comment]
1. 是不是可以默认当做有，最后一次点击选择点击进这里，几秒后再点击收藏的返回位置， 这样有的话可以点掉，没有的话进入收藏也可以自动退出

**Comment by xjw580** [comment]
也可以，下版本更新
