### ISSUE TITLE
添加好友对战和训练模式的支持

### ISSUE THREAD

**Issue by DnullP** [xjw580/Hearthstone-Script#80]
您好, 感谢您开发的插件平台, 我正在熟悉相关代码并编写套牌插件.

为了方便测试插件和套牌逻辑, 希望能够添加好友对战模式和训练模式的支持.

感谢您抽出时间回复与提供支持.

**Comment by xjw580** [comment]
你手动进入友谊赛的卡组选择界面后点击软件的开始应该是能正常运行的。
练习模式下个版本支持。

**Comment by xjw580** [comment]
[v4.1.1-TEST](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.1.1-TEST)中增加

**Comment by DnullP** [comment]
已测试可以正常使用, 感谢您的付出
