### ISSUE TITLE
获取窗口尺寸异常

### ISSUE THREAD

**Issue by huanghaiji666666** [xjw580/Hearthstone-Script#81]

**Comment by huanghaiji666666** [comment]
[hs_script.log](https://github.com/user-attachments/files/17670692/hs_script.log)

**Comment by xjw580** [comment]
[hs-script_v4.1.0-GA.zip](https://github.com/user-attachments/files/17672050/hs-script_v4.1.0-GA.zip)
下载后把zip改成jar，然后替换掉软件根目录的文件再试试

**Comment by huanghaiji666666** [comment]
一样 没什么区别

**Comment by huanghaiji666666** [comment]
[hs_script.log](https://github.com/user-attachments/files/17673980/hs_script.log)

**Comment by huanghaiji666666** [comment]
所以没办法了是吗

**Comment by huanghaiji666666** [comment]
我把炉石删了重装 扫描修复就好了,应该是句柄问题
