### ISSUE TITLE
挂机闪退问题

### ISSUE THREAD

**Issue by tyitheima** [xjw580/Hearthstone-Script#86]
现在最新版本经常性的就退出游戏了，不知道什么原因，是否是匹配时间过长导致的，除了设置中去设置匹配时间是否有其他程序上的bug

**Comment by John-bai-Smith** [comment]
你这个bug得别人能复现才行啊，我最近连着挂8小时也没有闪退过。很可能是自身操作系统问题、硬件性能问题、网络问题等等导致的。

**Comment by tyitheima** [comment]
因为我都是晚上挂机所以看不到具体情况，但我感觉应该是突然的匹配时间过长然后游戏不知道咋就退出了，就没有然后了。这个只能说是一味的拉长匹配时间吗，是否有其他的解决办法，程序上是否有做判断推出后重新进的代码

**Comment by xjw580** [comment]
> 因为我都是晚上挂机所以看不到具体情况，但我感觉应该是突然的匹配时间过长然后游戏不知道咋就退出了，就没有然后了。这个只能说是一味的拉长匹配时间吗，是否有其他的解决办法，程序上是否有做判断推出后重新进的代码

![image](https://github.com/user-attachments/assets/2fd397b2-8327-4fe0-b181-82805f89e621)

**Comment by tyitheima** [comment]
不行，我设置为10仍然会有游戏自动退出的现象

**Comment by xjw580** [comment]
> 不行，我设置为10仍然会有游戏自动退出的现象

闲置时间超过10分钟就是会重启游戏啊。
还有我都给你加`incomplete information`标签了，结果到现在都没见你贴日志，列为反面教材

**Comment by tyitheima** [comment]
怪我。今晚我着重看下问题，明天发日志

**Comment by tyitheima** [comment]
![Uploading 微信图片_20241113085314.png…]()

**Comment by tyitheima** [comment]
![微信图片_20241113085314](https://github.com/user-attachments/assets/83b4884d-14a1-4bce-bade-2fb0263b8b60)

**Comment by xjw580** [comment]
> ![微信图片_20241113085115](https://github.com/user-attachments/assets/28e04739-ebfb-4f45-8ec9-3dc7c2ee03d4)
> 这就是我说的不知道为啥直接退了

日志里不都写了嘛？长时间无作为重启游戏

**Comment by John-bai-Smith** [comment]
你的战网是不是没有以窗口形态打开，导致脚本没法重新启动炉石？
