### ISSUE TITLE
碰到後手腳本就擺爛了

### ISSUE THREAD

**Issue by cxie3949** [xjw580/Hearthstone-Script#87]
會把對面回合當自己回合 自己回合當對面回合 然後就啥也不幹

**Comment by lhlh0101** [comment]
可能是游戏语言的问题？我英文版的也这样，切成简体中文就好了

**Comment by cxie3949** [comment]
喔我完全没想到这个 我试试

lhlh0101 ***@***.***>於 2024年11月14日 週四，16:26寫道：
