### ISSUE TITLE
挂机掉线问题

### ISSUE THREAD

**Issue by tyitheima** [xjw580/Hearthstone-Script#88]
![微信图片_20241113085115](https://github.com/user-attachments/assets/43c4abd1-ab8e-428a-8ad9-b878d29c22a1)
![微信图片_20241113085314](https://github.com/user-attachments/assets/74cf2f1e-a6f8-477c-9ca5-7ccbe4f6c253)
不知道为什么2-3个小时候会掉线

**Comment by xjw580** [comment]
Duplicate of #86

**Comment by tyitheima** [comment]
不好意思，刚才没刷出来
