### ISSUE TITLE
感谢大佬！新手学习请教注入dll的作用是什么

### ISSUE THREAD

**Issue by magicchao** [xjw580/Hearthstone-Script#89]
看起来主要是通过日志分析游戏信息，然后模拟鼠标点击来进行交互
那注入libHS.dll的作用是什么呢？谢谢大佬分享！

**Comment by xjw580** [comment]
进去当内应，里应外合用的

**Comment by magicchao** [comment]
> 进去当内应，里应外合用的

具体有啥功能需要内应哈？分析日志、模拟鼠标这些都不需要，能透露一下下不

**Comment by magicchao** [comment]
好像也没看到进程通讯的代码，从内应获取什么信息

**Comment by xjw580** [comment]
hook游戏内某些系统库的函数，让游戏调用函数时只能得到我设定的值

**Comment by magicchao** [comment]
嗯嗯 譬如用于反外挂检测之类的么

**Comment by xjw580** [comment]
> 嗯嗯 譬如用于反外挂检测之类的么

 差不多
