### ISSUE TITLE
【疑似BUG】运行一段时间后后，会切换到第二页的第一个卡组

### ISSUE THREAD

**Issue by John-bai-Smith** [xjw580/Hearthstone-Script#96]
第一页第一个卡组为海盗瞎，第二页第一个卡组为鱼人萨，
根据log显示，第26把游戏使用海盗瞎获胜，结果第27把游戏开始使用鱼人萨了。
[hs_script.log](https://github.com/user-attachments/files/17796519/hs_script.log)

**Comment by xjw580** [comment]
应该是下一页的按钮和其他按钮重合了，下版本优化

**Comment by xjw580** [comment]
[v4.2.0-GA](https://github.com/xjw580/Hearthstone-Script/releases/tag/v4.2.0-GA)已优化
