### ISSUE TITLE
[Bug]: 胜率统计错误

### ISSUE THREAD

**Issue by John-bai-Smith** [xjw580/Hearthstone-Script#98]
### 预期情况

胜率统计与火石插件一致

### 实际情况

胜率统计与火石插件不一致，hs-script里显示72局45.9%胜率，火石插件显示72局62.5%胜率

### 复现方法

无特殊复现方法

### 日志信息

[hs_script.log](https://github.com/user-attachments/files/17853766/hs_script.log)
[hs_script-2024-11-21.0.log](https://github.com/user-attachments/files/17853767/hs_script-2024-11-21.0.log)

### 我确认已更新至最新版本

- [X] 是

### 我确认已查询历史issues及参阅QUESTION

- [X] 是

**Comment by xjw580** [comment]
总局数是否和火石一致

**Comment by xjw580** [comment]
自己用局数*胜率算下胜场，然后看加了几颗星，如果在传说当我没说
