### ISSUE TITLE
[Feature request]: 直伤法术瞄准对方而不是自己

### ISSUE THREAD

**Issue by John-bai-Smith** [xjw580/Hearthstone-Script#99]
### 相关问题

激进策略下打出直伤法术每次都打自己的随从

### 描述你希望的解决方案

能不能优化成只会打对方的随从或英雄，就算随机选目标也行

### 我确认已查询历史issues

- [X] 是

**Comment by xjw580** [comment]
v4.2.2-DEV已支持识别简单的伤害法术
